"""add titular and estado to marcas

Revision ID: 945716631896
Revises: d0455994f299
Create Date: 2025-08-24 21:29:00.527476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945716631896'
down_revision: Union[str, Sequence[str], None] = 'd0455994f299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marcas', sa.Column('titular', sa.String(length=100), nullable=True))
    op.add_column('marcas', sa.Column('estado', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marcas', 'estado')
    op.drop_column('marcas', 'titular')
    # ### end Alembic commands ###
